### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [rodchenk/xenia#3]
Hello Xenia team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the Xenia project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>
```

We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by rodchenk** [comment]
Hello @miklossy,
thank you for your offer

```html
<tr>
	<td><a href="https://github.com/rodchenk/xenia">xenia</a></td>
	<td>DSL for the rapid creation of static websites based on a sitemap with precompiled templates</td>
	<td>MIT</td>
	<td>Language, Web Development</td>
	<td>Mischa Rodchenkov</td>
</tr>
```

Best Regards
Mischa

**Comment by miklossy** [comment]
Thank you Mischa!

**Comment by miklossy** [comment]
The `xenia` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
